name: Waka Readme

on:
  schedule:
    # Executa à 00:00 IST
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: Pjmaciel/waka-readme-stats@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_TOTAL_CODE_TIME: ¨True"
          SHOW_PROJECTS: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          LOCALE: "pt-BR"
